### PR TITLE
#499 - Fix incorrect date style in feed

### LINKED ISSUE #499: Incorrect font style and letters are cut off for feed cards, that have 2 line descriptions.
User experiences that the following card contains an incorrect font style.

AEM:  
Image

User also experiences that feed cards that have a 2 line description, have some letters that look like they are being cut off from the title

AEM:  

Image

### PR DESCRIPTION
**Pull request by tbxsaugat**
Fix incorrect date style in feed.

Fix #499 

Test URLs:
- Before: https://main--creditacceptance--aemsites.aem.page/car-buyers/express-lane
- After: https://smalla-499--creditacceptance--aemsites.aem.page/car-buyers/express-lane
Testing criteria - Look for "Long-Lasting Vehicles of 2021" card title under "Car Buying Tips and Guides" category.

### CODE REVIEW

File: blocks/cards/cards.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { initSlider } from '../../libs/utils/decorate.js';
 const isDesktop = window.matchMedia('(min-width: 960px)');
 
 export function isDateValid(dateStr) {
-  if (!dateStr || typeof dateStr !== 'string') return false;
+  if (!dateStr || typeof dateStr !== 'string' || dateStr.length > 18) return false;
```
Comment (kailasnadh790) [inline blocks/cards/cards.js:8]: wouldn't this fail if the title is "Long-Lasting Vehicles of 20 May 2021" ?

**Review by kailasnadh790 — CHANGES_REQUESTED** [review]
